### ISSUE TITLE
Enhancement or Error / Not working on iPhone device

### ISSUE THREAD

**Issue by warnerbryce** [sadponyguerillaboy/Apple-Serial-Number-Decoder#2]
Hello,

Thank you for this great tool, i can escape the bad Captcha on checkcover at apple dot com.
I just made a few tests and the Decode don't work for iPhone.
I get a PHP error : on line 357 and 361 of serialinfo.php 
Undefined variable $modelnum

Does it something that can be fixed or the iPhone is completly different and won't work with this tool ? 
Good day to you.

**Comment by sadponyguerillaboy** [comment]
which model of iphone and what are the last 4 digits of the serial?

**Comment by warnerbryce** [comment]
Hi @sadponyguerillaboy, 

i have problems with iMac that are under 2019 too... 
Same PHP error but on the server when i do a CURL with the link you gave me, i get the correct answer.

**Comment by sadponyguerillaboy** [comment]
Would you mind emailing me the serials your having issues with so I can attempt to replicate the problem. Haven't used php in a while, but could set something up to mimic your conditions. My email is on my profile page.

**Comment by sadponyguerillaboy** [comment]
issues have been corrected. please use the new updated serialinfo.php. it has been optimized for php8.0. ther were a few minor differences pertaining to stringent variable declaration and sorting / arrary to string conversions. also make sure to correctly chmod the permissions for database.json

**Comment by warnerbryce** [comment]
Yeah, it works now. 
Thank you.... I just don't understand why i had this same error with PHP 7.4 ...
